// Generated by CoffeeScript 1.9.3
(function() {
  var SortMap, exports, groupBy, through;

  through = require('through');

  SortMap = require('sortset').SortMap;

  exports = module.exports = groupBy = function(ruler) {
    var end, s, write;
    write = function(doc) {};
    end = function() {};
    s = through(write, end);
    return s;
  };

}).call(this);

//# sourceMappingURL=groupby.js.map
